# Generated by Django 4.1 on 2022-09-08 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descricao_curta', models.TextField(blank=True, max_length=20)),
                ('autor', models.CharField(max_length=20)),
                ('conteudo', models.TextField(max_length=500)),
                ('imagem', models.ImageField(upload_to='')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publicacoes.categoria')),
            ],
        ),
    ]
