# Generated by Django 4.1 on 2022-09-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='imagem',
        ),
    ]
