# Generated by Django 4.1 on 2022-09-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0002_remove_publicacao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='descricao_curta',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
