# Generated by Django 4.1 on 2022-09-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0003_alter_categoria_nome_alter_publicacao_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='autor',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='conteudo',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='descricao_curta',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(max_length=1000),
        ),
    ]
