# Generated by Django 4.1 on 2022-09-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0005_alter_publicacao_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='conteudo',
            field=models.TextField(max_length=10000),
        ),
    ]
